export const String = {
    //GateEntry, QATest and Inward strings
    please_select_pdf : "Please select a PDF file.",
    please_select_jpg : "Please select a JPG file.",
    qty_must_not_zero : "Qty per board must be a non-zero number",
    gate_entry : "Gate Entry",
    order_details_text : "Order Details",
    order_num_text : "Order number",
    received_data_text : "Received Date",
    sender_name : "Sender name",
    sender_contact_number : "Sender contact number",
    invoice_number : "Invoice number",
    upload_invoice : "Upload Invoice",
    upload_photo : "Upload Box Photo",
    cancel_btn : "Cancel",
    mark_as_received_btn : "Mark as Received",
    Loading_text : "Loading...",
    qa_test_document : "QA Test Document",
    qa_date : "QA Date",
    inward_id_text : "Inward ID",
    qa_test : "QA Test",
    ordered_numbered_text : "Ordered Number",
    vendor_id : "Vendor Id",
    order_date : "Order Date",
    batch_no : "Batch no",
    upload_confirmation_documents : "Upload Confirmation Documents",
    inward_purchase : "Inward Purchase",
    description : "Description",
    comments : "Comments"
}